config/routes.rb
Rails.application.routes.draw do
  root 'stores#index'
  devise_for :users
  resources :stores do
    resources :votes, only: [:create]
  end
  resources :contacts, only:[:new, :create]
end

app/models/store.rb
class Store < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :user

  has_many :warehouses
  has_many :products, through: :warehouses

  has_many :votes
  has_many :users, through: :votes

  def information
    "#{self.name} (地址：#{
    if self.adress.present?
      self.adress
    else
      '未填寫'
    end
    }, 電話：#{
    if self.tel.present?
      self.tel
    else
      '未填寫'
    end
    })"
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :find_store, only:[:destroy, :show, :edit, :update]

  def index
    @stores = Store.page(params[:page]).order('votes_count DESC').per(10)
  end

  def destroy
    @store.destroy
    flash[:notice] = "已刪除商店"
    redirect_to stores_path
  end

  def show
  end

  def edit
  end

  def update
    if @store.update(store_params)
      flash[:notice] = "商店更新成功"
      redirect_to stores_path
    else
      render :edit
    end
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      flash[:notice] = "成功新增商店"
      redirect_to stores_path
    else
      render :new
    end
  end

  def new
    @store = Store.new
  end

  private
  def store_params
    params.require(:store).permit(:name, :adress, :tel)
  end

  def find_store
    @store = Store.find_by(id: params[:id])
  end
end

app/helpers/stores_helper.rb
module StoresHelper
  def store_information(store)
    "#{store.name} (地址：#{
    if store.adress.present?
      store.adress
    else
      '未填寫'
    end
    }, 電話：#{
    if store.tel.present?
      store.tel
    else
      '未填寫'
    end
    })"
  end
end

app/views/stores/_form.html.erb
<% if @store.errors.any? %>
<div class="panel panel-danger">
  <div class="panel-heading">錯誤訊息</div>
  <div class="panel-body">
    <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<%= form_for(@store) do |f| %>
  <%= f.label :name, "名稱" %>
  <%= f.text_field :name, class:'form-control', placeholder:'請填寫商店名稱' %>
  <br />

  <%= f.label :adress, "地址" %>
  <%= f.text_field :adress, class:'form-control', placeholder:'請填寫商店地址' %>

  <br />
  <%= f.label :tel, "電話" %>
  <%= f.text_field :tel, class:'form-control', placeholder:'請填寫商店電話' %>

  <br />
  <%= f.submit '送出', class:'btn btn-primary' %>
  <br />
  <br />
<% end %>

app/views/stores/edit.html.erb
<h1>編輯商店</h1>

<%= render 'form' %>

app/views/stores/index.html.erb
<h1>Welcome to my store</h1>

<%= link_to "新增商店", new_store_path, class:'btn btn-primary' %>
<table class="table table-hover">
  <thead>
    <tr>
      <td>店家名稱</td>
      <td>票選數</td>
      <td></td>
    </tr>
  </thead>
<% @stores.each do |store| %>
  <tr>
    <td><%= link_to store.information, store %></td>
    <td><%= store.votes.size %></td>
    <td>
      <%= link_to "票選", store_votes_path(store), method: :post, class:'btn btn-success', data:{confirm:"確定投給#{store.name}商家嗎?"} %>
      <%= link_to "編輯", edit_store_path(store), class:'btn btn-success' %>
      <%= link_to "刪除", store, method: :delete, class:'btn btn-danger', data:{confirm: 'are you sure'} %></td>
  </tr>
<% end %>
</table>
<%= paginate @stores, theme: 'twitter-bootstrap-3' %>

app/views/stores/new.html.erb
<h1>新增商店</h1>

<%= render 'form' %>

app/views/stores/show.html.erb
<h1><%= @store.name %></h1>
地址：<%= @store.adress %><br />
電話：<%= @store.tel %><br />

<%= link_to "商店列表", stores_path %>